import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useState } from 'react';
import Link from 'next/link'



export default function Home() {
  const [searchResult, setSearchResult] = useState([]);
  const [searchKeyword, setSearchKeyword] = useState("");
  const [isSearching, setIsSearching] = useState(false);
  const [searchIn, setSearchIn] = useState('Definisi');


  const query = async () => {
    setIsSearching(true);
    setSearchResult([]);
    const inputQuery = document.querySelector('#inputQuery') as HTMLInputElement;
    setSearchKeyword(inputQuery.value);

    if (!inputQuery.value) {
      setIsSearching(false);
      return
    }

    let ENDPOINT = `https://kamus-hukum.herokuapp.com/api/v1/db/data/v1/kamus-hukum/Kamus?limit=10&offset=0&where=(${searchIn},like,${inputQuery.value})`

    let response = await fetch(ENDPOINT, {
      headers: {
        'xc-auth': process.env.NEXT_PUBLIC_AUTH,
      }
    });

    response = await response.json();
    console.log(response)
    setSearchResult(response['list']);
    setIsSearching(false);
  }

  const handleSearchEnter = (event) => {
    if (event.keyCode === 13) {
      query()
    }
  }

  const handleSearchIn = event => {
    setSearchIn(event.target.value);
  }

  const markText = (text: string, keyword: string): string => {
    if (!keyword || keyword.length == 0) {
      return text;
    }

    return text.replace(
      new RegExp(keyword, "gi"),
      (match) => `<span class="bg-yellow-100">${match}</span>`,
    );
  }

  const clipboard = (text) => {
    navigator.clipboard.writeText(text);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Kamus Hukum</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className="flex w-full bg-slate-200 min-h-screen h-auto justify-center">
          <div className="max-w-lg w-full p-3">
            <h1 className='font-serif pt-10 h-auto text-center text-3xl text-slate-600 w-full align-center font-bold'>Kamus Hukum Indonesia</h1>
            <div className='my-2 mx-2 relative flex justify-center'>
              <Link href="/about">
                <a className="mx-2 font-semibold underline" href=""><span>Tentang</span></a>
              </Link> |
              <Link href="/contributor">
                <a className="mx-2 font-semibold underline" href=""><span>Kontributor</span></a>
              </Link>
              |
              <Link href="/disclaimer">
                <a className="mx-2 font-semibold underline" href=""><span>Disclaimer</span></a>
              </Link>
            </div>
            <div className='mt-10 mx-2 relative'>
              <input type="text" className="h-14 w-full pl-5 pr-20 rounded-lg z-0 focus:shadow focus:outline-none shadow-lg" id="inputQuery" placeholder="Cari istilah hukum di sini..." onKeyDown={(e) => handleSearchEnter(e)} />
              <div className="absolute top-2 right-2">
                <button className="h-10 w-20 text-white rounded-lg bg-blue-500 hover:bg-red-/600" onClick={() => query()}>Cari</button>
              </div>
            </div>

            <div className="flex justify-center mt-5">
              <div className="form-check form-check-inline mx-2">
                <input className="form-check-input form-check-input appearance-none rounded-full h-4 w-4 border border-gray-300 bg-white checked:bg-blue-600 checked:border-blue-600 focus:outline-none transition duration-200 mt-1 align-top bg-no-repeat bg-center bg-contain float-left mr-2 cursor-pointer" type="radio" name="ROSearchIn" id="inlineRadio1" value="Definisi" onChange={e => handleSearchIn(e)} checked={searchIn=='Definisi'}/>
                <label className="form-check-label inline-block text-gray-800 cursor-pointer">Terminologi</label>
              </div>
              <div className="form-check form-check-inline mx-2">
                <input className="form-check-input form-check-input appearance-none rounded-full h-4 w-4 border border-gray-300 bg-white checked:bg-blue-600 checked:border-blue-600 focus:outline-none transition duration-200 mt-1 align-top bg-no-repeat bg-center bg-contain float-left mr-2 cursor-pointer" type="radio" name="ROSearchIn" id="inlineRadio2" value="Keterangan" onChange={e => handleSearchIn(e)} checked={searchIn=='Keterangan'}/>
                <label className="form-check-label inline-block text-gray-800 cursor-pointer">Penjelasan</label>
              </div>
            </div>

            <div className="w-full flex mt-4 px-2">
              <div className="w-full block rounded-lg shadow-lg bg-white text-left ">
                {searchResult && searchResult.length > 0 && (
                  <div className="py-3 px-6 border-b border-gray-300 font-medium">
                    Hasil Pencarian
                  </div>
                )
                }

                {
                  isSearching && (
                    <div className="w-full p-6 border-b border-gray-300">
                      <div className="animate-pulse text-gray-700 text-base">
                        <div className="w-full bg-gray-300 h-4 rounded-md mb-2"></div>
                        <div className="w-full bg-gray-300 h-4 rounded-md mb-2"></div>
                        <div className="w-full bg-gray-300 h-4 rounded-md mb-2"></div>
                        <div className='w-full flex justify-end mt-5'>
                          <div className="w-10 mx-1 bg-gray-300 h-6 rounded-md mb-2"></div>
                          <div className="w-10 mx-1 bg-gray-300 h-6 rounded-md mb-2"></div>
                          <div className="w-10 mx-1 bg-gray-300 h-6 rounded-md mb-2"></div>
                        </div>
                      </div>
                    </div>
                  )
                }
                {searchResult.map(item => {
                  return (
                    <div className="w-full p-6 border-b border-gray-300" key={item.Id}>
                      <a href={item.Url} target="_blank" rel="noreferrer"><span className="text-xs inline-block py-1 px-2 uppercase rounded bg-slate-200 uppercase mb-3">
                        {item.Sumber}
                      </span></a>
                      <p className="text-gray-700 text-base mb-4" dangerouslySetInnerHTML={{ __html: '<b>' + markText(item.Definisi, searchKeyword) + '</b> <br/>' + markText(item.Keterangan, searchKeyword) }}>

                      </p>
                      <div className='w-full flex justify-end'>
                        <button type="button" className="inline-block p-2 bg-slate-400 text-white font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-slate-700 hover:shadow-lg" onClick={e => clipboard(item.Keterangan)}>
                          <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M8 5H6a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2v-1M8 5a2 2 0 002 2h2a2 2 0 002-2M8 5a2 2 0 012-2h2a2 2 0 012 2m0 0h2a2 2 0 012 2v3m2 4H10m0 0l3-3m-3 3l3 3"></path></svg>
                        </button>
                      </div>
                    </div>

                  )
                })}
              </div>
            </div>
          </div>
        </div>
      </main >


    </div >
  )
}
