import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Kamus Hukum</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className="flex w-full bg-slate-200 h-screen justify-center">
          <div className='max-w-lg w-full'>
            <h1 className='pt-10 h-auto text-center text-3xl text-slate-600 w-full align-center font-bold'>Kamus Hukum Indonesia</h1>
            <div className='mt-10 mx-2 relative'>
              <input type="text" className="h-14 w-full pl-5 pr-20 rounded-lg z-0 focus:shadow focus:outline-none shadow-lg" placeholder="Cari istilah hukum di sini..." />
              <div class="absolute top-2 right-2">

                <button className="h-10 w-20 text-white rounded-lg bg-blue-500 hover:bg-red-600">Cari</button>

              </div>
            </div>

            <div className="w-full flex mt-4 px-2">
              <div className="block rounded-lg shadow-lg bg-white text-left ">
                <div className="py-3 px-6 border-b border-gray-300 font-medium">
                  Hasil Pencarian
                </div>

                {[1, 2, 3].map(function (d, idx) {
                  return (
                    <div className="p-6 border-b border-gray-300">
                      <p className="text-gray-700 text-base mb-4">
                        With supporting text below as a natural lead-in to additional content.
                      </p>
                      <div className='w-full flex justify-end'>
                        <button type="button" className="inline-block p-2 bg-slate-400 text-white font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-slate-700 hover:shadow-lg">Salin</button>
                        <button type="button" className="inline-block mx-2 p-2 bg-slate-400 text-white font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-slate-700 hover:shadow-lg">Bookmark</button>
                        <button type="button" className="inline-block p-2 bg-slate-400 text-white font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-slate-700 hover:shadow-lg">Source</button>
                      </div>
                    </div>

                  )
                })}
              </div>


            </div>
          </div>




        </div>
      </main >


    </div >
  )
}
